package platform

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"strings"
)

// genericHostnames are OS hostnames that indicate a fresh install or live ISO
// and should be replaced with a citadel-<id> name. Anything not in this list
// is treated as a user-chosen hostname worth preserving.
var genericHostnames = map[string]bool{
	"":            true,
	"localhost":   true,
	"debian":      true,
	"ubuntu":      true,
	"fedora":      true,
	"archlinux":   true,
	"nixos":       true,
	"raspberrypi": true,
	"linux":       true,
	"host":        true,
	"changeme":    true,
	"default":     true,
}

// IsGenericHostname returns true if the hostname looks like a default OS
// hostname that should be replaced during Citadel registration.
func IsGenericHostname(name string) bool {
	lower := strings.ToLower(strings.TrimSpace(name))
	return genericHostnames[lower]
}

// machineIDPath is the path to the machine-id file. Overridable in tests.
var machineIDPath = "/etc/machine-id"

// GenerateCitadelHostname generates a hostname like "citadel-<short_id>" for use
// during node initialization. The short_id is derived from /etc/machine-id (first
// 8 characters) when available, or a random 8-character hex string as fallback.
//
// This ensures nodes get unique, recognizable names instead of inheriting generic
// OS hostnames like "debian" on live ISOs.
func GenerateCitadelHostname() (string, error) {
	shortID, err := getShortMachineID()
	if err != nil {
		shortID, err = generateRandomHexID(8)
		if err != nil {
			return "", fmt.Errorf("failed to generate hostname: %w", err)
		}
	}
	return "citadel-" + shortID, nil
}

// autoGeneratedHostnamePattern matches hostnames produced by
// GenerateCitadelHostname: the "citadel-" prefix followed by an 8-character
// lowercase hex short ID (e.g. "citadel-a3f2b81c").
var autoGeneratedHostnamePattern = regexp.MustCompile(`^citadel-[0-9a-f]{8}$`)

// IsAutoGeneratedHostname returns true if the given name was auto-generated by
// GenerateCitadelHostname (i.e. matches the "citadel-<8 hex>" pattern). This is
// used during re-registration to detect machine-generated names and offer the
// user a chance to set a friendlier one.
func IsAutoGeneratedHostname(name string) bool {
	return autoGeneratedHostnamePattern.MatchString(strings.ToLower(strings.TrimSpace(name)))
}

// IsValidHostname reports whether name is a syntactically valid hostname label
// suitable for both the OS hostname and the Headscale node name. Rules follow
// RFC 1123: 1-63 characters, alphanumeric or hyphen, not starting or ending
// with a hyphen.
func IsValidHostname(name string) bool {
	name = strings.TrimSpace(name)
	if len(name) == 0 || len(name) > 63 {
		return false
	}
	return validHostnamePattern.MatchString(name)
}

// validHostnamePattern matches a single RFC 1123 hostname label.
var validHostnamePattern = regexp.MustCompile(`^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?$`)

// getShortMachineID reads the machine-id file and returns its first 8 characters.
// Returns an error if the file is missing, empty, or shorter than 8 characters.
func getShortMachineID() (string, error) {
	data, err := os.ReadFile(machineIDPath)
	if err != nil {
		return "", fmt.Errorf("could not read %s: %w", machineIDPath, err)
	}

	id := strings.TrimSpace(string(data))
	if len(id) < 8 {
		return "", fmt.Errorf("%s too short: %q", machineIDPath, id)
	}

	return id[:8], nil
}

// generateRandomHexID generates a random hex string of the specified length.
func generateRandomHexID(length int) (string, error) {
	// We need length/2 bytes (rounded up) to produce `length` hex chars
	numBytes := (length + 1) / 2
	b := make([]byte, numBytes)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("failed to generate random bytes: %w", err)
	}
	return hex.EncodeToString(b)[:length], nil
}

// SetHostname attempts to set the system hostname. This is best-effort and will
// return an error if it fails (e.g., when not running as root). Callers should
// treat failure as non-fatal — the generated hostname is still used for Headscale
// registration regardless of whether the OS hostname is updated.
//
// On Linux: tries hostnamectl, falls back to writing /etc/hostname + syscall.
// On other platforms: no-op (returns nil).
func SetHostname(name string) error {
	if !IsLinux() {
		return nil
	}

	// Try hostnamectl first (sets both transient and static hostname)
	if err := exec.Command("hostnamectl", "set-hostname", name).Run(); err == nil {
		return nil
	}

	// Fallback: write /etc/hostname for persistence across reboots
	if err := os.WriteFile("/etc/hostname", []byte(name+"\n"), 0644); err != nil {
		return fmt.Errorf("failed to write /etc/hostname: %w", err)
	}

	// Also set the transient hostname for the current session
	if err := exec.Command("hostname", name).Run(); err != nil {
		return fmt.Errorf("failed to set transient hostname: %w", err)
	}

	return nil
}
