# services/compose/lmstudio.yml

services:
  lmstudio:
    image: technovangelist/lm-studio:latest
    container_name: citadel-lmstudio
    ports:
      - "1234:1234"
    volumes:
      # Mount a user-accessible directory for LM Studio's cache and models
      - ~/citadel-cache/lmstudio:/root/.cache/lm-studio
    environment:
      - DOCKER=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
