# services/compose/ollama.yml

services:
  ollama:
    image: ollama/ollama:latest
    container_name: citadel-ollama
    ports:
      - "11434:11434"
    volumes:
      # Mount a user-accessible directory for Ollama models
      - ~/citadel-cache/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
