# services/compose/vllm.yml

services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: citadel-vllm
    ports:
      - "8000:8000"
    volumes:
      # Mount a user-accessible directory to cache Hugging Face models
      - ~/citadel-cache/huggingface:/root/.cache/huggingface
    command: --host 0.0.0.0 --port 8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
