//go:build linux

package service

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Re-materialization of managed systemd unit files on binary upgrade (#444/#426).
//
// The problem: #444 hardened the systemd unit TEMPLATES (StartLimitIntervalSec,
// StartLimitBurst, RestartSteps, RestartMaxDelaySec) to stop a 10s crash-restart
// storm from self-DoSing the control plane. But `citadel update install` swaps
// only the BINARY; the unit file already on disk (written once by install.sh,
// packer, or `citadel service install`) is never re-rendered. So every node that
// was deployed by an older binary keeps its old restart-storm unit forever and
// the hardening never reaches the fleet -- the same "materialized once, never
// refreshed on version change" class as #426 (compose files).
//
// The fix: on `citadel update install` (and, version-gated, on the next boot
// after an upgrade), re-materialize the citadel-MANAGED unit files by injecting
// the four hardening directives at their correct values, then daemon-reload.
//
// Why field-injection instead of full template regeneration:
//   - There are two distinct deployed unit families with DIFFERENT content:
//     `citadel-worker.service` (install.sh / packer -- the actual fleet: system
//     unit, root, HOME=/root, LimitNOFILE, WorkingDirectory, docker.service) and
//     `citadel.service` (`citadel service install`, user or system, generated by
//     GenerateUnitFile). Their ExecStart/User/HOME/extra directives differ.
//   - Regenerating either from a single embedded template would clobber
//     install-specific content (or, for the system worker, require reproducing a
//     shell heredoc we do not embed) and could reset operator-set fields.
//   - Injecting ONLY the hardening directives is minimal, precise, and idempotent:
//     it changes exactly the lines #444 added and nothing else, so a node whose
//     unit is already hardened is left byte-for-byte untouched (no needless
//     daemon-reload/restart churn).
//
// We never touch a file that is not citadel-managed (see isCitadelManagedUnit),
// and we back up the prior content to <unit>.citadel-bak before rewriting so an
// operator can recover their exact previous file.

// hardeningDirectives are the systemd directives #444 added to defend against a
// crash-restart storm. Order matters only for where we insert a missing one:
// StartLimit* belong in [Unit]; Restart* belong in [Service].
const (
	dirStartLimitIntervalSec = "StartLimitIntervalSec"
	dirStartLimitBurst       = "StartLimitBurst"
	dirRestartSteps          = "RestartSteps"
	dirRestartMaxDelaySec    = "RestartMaxDelaySec"
)

// unitHardening is the desired value for each hardening directive and the
// section it belongs to.
type unitHardening struct {
	key     string
	value   string
	section string // "Unit" or "Service"
}

var wantHardening = []unitHardening{
	{dirStartLimitIntervalSec, "300", "Unit"},
	{dirStartLimitBurst, "5", "Unit"},
	{dirRestartSteps, "5", "Service"},
	{dirRestartMaxDelaySec, "300", "Service"},
}

// managedUnitCandidate is one place a citadel-managed systemd unit may live.
type managedUnitCandidate struct {
	path     string
	userMode bool
}

// candidateManagedUnits returns every path a citadel-managed systemd unit could
// occupy on this host, across the deployment methods:
//   - /etc/systemd/system/citadel-worker.service : install.sh + packer (fleet)
//   - /etc/systemd/system/citadel.service        : `citadel service install --system`
//   - ~/.config/systemd/user/citadel.service     : `citadel service install`
//
// Non-existent paths are simply skipped by the caller. We deliberately include
// the user unit even when running as root (update-as-root is common): if a user
// unit exists we still normalize it.
func candidateManagedUnits() []managedUnitCandidate {
	cands := []managedUnitCandidate{
		{filepath.Join("/etc/systemd/system", "citadel-worker.service"), false},
		{filepath.Join("/etc/systemd/system", ServiceName+".service"), false},
	}
	if p, err := unitFilePath(true); err == nil {
		cands = append(cands, managedUnitCandidate{p, true})
	}
	return cands
}

// isCitadelManagedUnit reports whether the given unit content was written by
// citadel (install.sh, packer, or `citadel service install`) and is therefore
// safe to normalize. We match on the stable markers every citadel unit carries:
// a Citadel Description plus an ExecStart that invokes the citadel binary with
// the `work` subcommand. This intentionally refuses to touch an unrelated unit
// that merely happens to sit at one of our candidate paths.
func isCitadelManagedUnit(content string) bool {
	hasCitadelDesc := false
	hasCitadelExec := false
	for _, raw := range strings.Split(content, "\n") {
		line := strings.TrimSpace(raw)
		switch {
		case strings.HasPrefix(line, "Description="):
			if strings.Contains(strings.ToLower(line), "citadel") {
				hasCitadelDesc = true
			}
		case strings.HasPrefix(line, "ExecStart="):
			// e.g. ExecStart=/usr/local/bin/citadel work
			if strings.Contains(line, "citadel") && strings.Contains(line, " work") {
				hasCitadelExec = true
			}
		}
	}
	return hasCitadelDesc && hasCitadelExec
}

// hardenUnitContent returns unit content with every #444 hardening directive
// present at its desired value. It is pure (no I/O) and idempotent: calling it on
// already-hardened content returns byte-identical output. An existing directive
// with a different/stale value is rewritten in place; a missing one is appended
// to the end of its owning section ([Unit] or [Service]). Comments and all other
// lines are preserved verbatim. The second return reports whether anything
// changed.
func hardenUnitContent(content string) (string, bool) {
	// Preserve the original line endings shape: split on "\n"; a trailing
	// newline yields a trailing "" element which we keep so the file still ends
	// in a newline after we rejoin.
	lines := strings.Split(content, "\n")

	// Index of the header line for each section, and the index of the last
	// content line within it (where we append a missing directive).
	sectionInsertAt := map[string]int{} // section -> insert index (exclusive end of section body)
	sectionSeen := map[string]bool{}

	// First pass: rewrite existing hardening directives in place and locate
	// section boundaries.
	wantBySection := map[string]map[string]string{"Unit": {}, "Service": {}}
	for _, h := range wantHardening {
		wantBySection[h.section][h.key] = h.value
	}

	changed := false
	curSection := ""
	for i, raw := range lines {
		trimmed := strings.TrimSpace(raw)
		if strings.HasPrefix(trimmed, "[") && strings.HasSuffix(trimmed, "]") {
			curSection = strings.TrimSuffix(strings.TrimPrefix(trimmed, "["), "]")
			sectionSeen[curSection] = true
			sectionInsertAt[curSection] = i + 1
			continue
		}
		// Track the end of the current section body (last non-empty index + 1),
		// so we insert a missing directive right after the last real line rather
		// than after trailing blank lines.
		if curSection != "" && trimmed != "" {
			sectionInsertAt[curSection] = i + 1
		}
		// Rewrite an existing hardening directive if its value is stale.
		if want, ok := wantBySection[curSection]; ok && strings.Contains(trimmed, "=") {
			key := strings.TrimSpace(strings.SplitN(trimmed, "=", 2)[0])
			if val, isHardening := want[key]; isHardening {
				desired := key + "=" + val
				if trimmed != desired {
					lines[i] = desired
					changed = true
				}
				delete(want, key) // mark as present; do not re-append below
			}
		}
	}

	// Second pass: append any directive still missing from its section. We insert
	// from the bottom-most index upward so earlier insert positions stay valid.
	type pendingInsert struct {
		at   int
		line string
	}
	var inserts []pendingInsert
	for _, h := range wantHardening {
		remaining := wantBySection[h.section]
		if _, stillMissing := remaining[h.key]; !stillMissing {
			continue // was rewritten/found above
		}
		if !sectionSeen[h.section] {
			// Section header absent entirely -- refuse to guess where to graft it
			// (this is not a citadel unit shape we recognize). Leave it to the
			// managed-marker guard; do not fabricate a section.
			continue
		}
		inserts = append(inserts, pendingInsert{
			at:   sectionInsertAt[h.section],
			line: h.key + "=" + h.value,
		})
		changed = true
	}

	if len(inserts) == 0 {
		if !changed {
			return content, false
		}
		return strings.Join(lines, "\n"), true
	}

	// Apply inserts from highest index to lowest so indices remain valid.
	for i := 0; i < len(inserts); i++ {
		for j := i + 1; j < len(inserts); j++ {
			if inserts[j].at > inserts[i].at {
				inserts[i], inserts[j] = inserts[j], inserts[i]
			}
		}
	}
	for _, ins := range inserts {
		at := ins.at
		if at > len(lines) {
			at = len(lines)
		}
		lines = append(lines[:at], append([]string{ins.line}, lines[at:]...)...)
	}

	return strings.Join(lines, "\n"), true
}

// RematerializeManagedUnits re-renders every citadel-managed systemd unit on disk
// so the #444 crash-storm hardening reaches nodes deployed by an older binary. It
// is safe to call on every `citadel update install` and (version-gated) at boot:
// a unit already carrying the hardening is left untouched and triggers no
// daemon-reload. logf may be nil.
//
// Returns the list of unit paths it actually rewrote (empty when everything was
// already current). Errors on individual units are logged and do not abort the
// others; the returned error is non-nil only for a systemic failure.
func RematerializeManagedUnits(logf func(format string, args ...any)) ([]string, error) {
	log := func(format string, args ...any) {
		if logf != nil {
			logf(format, args...)
		}
	}

	var rewritten []string
	reloadUser := false
	reloadSystem := false

	for _, cand := range candidateManagedUnits() {
		data, err := os.ReadFile(cand.path)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			log("unit-refresh: %s: read failed, skipping: %v", cand.path, err)
			continue
		}
		content := string(data)

		if !isCitadelManagedUnit(content) {
			log("unit-refresh: %s: not a citadel-managed unit; leaving untouched", cand.path)
			continue
		}

		hardened, changed := hardenUnitContent(content)
		if !changed {
			continue // already current: no write, no reload churn
		}

		// System units live under /etc and require root to rewrite. Skip (with a
		// hint) rather than error when we lack privileges, e.g. an unprivileged
		// `citadel update install` on a system-unit node.
		if !cand.userMode && os.Geteuid() != 0 {
			log("unit-refresh: %s: needs the #444 restart-storm hardening but rewriting a system unit requires root; re-run `sudo citadel update install` (or reinstall) to apply", cand.path)
			continue
		}

		if err := backupUnit(cand.path); err != nil {
			log("unit-refresh: %s: backup failed, skipping rewrite: %v", cand.path, err)
			continue
		}
		if err := writeUnitFile(cand.path, hardened); err != nil {
			log("unit-refresh: %s: write failed: %v", cand.path, err)
			continue
		}
		rewritten = append(rewritten, cand.path)
		if cand.userMode {
			reloadUser = true
		} else {
			reloadSystem = true
		}
		log("unit-refresh: %s: applied #444 restart-storm hardening (backup at %s.citadel-bak)", cand.path, cand.path)
	}

	// daemon-reload so systemd re-reads the changed unit. We do NOT restart the
	// worker: the update flow handles restart on its own terms and a surprise
	// mid-update restart would drop in-flight jobs. The new unit takes effect on
	// the next (natural or update-driven) restart.
	if reloadSystem {
		if err := runCmd("systemctl", "daemon-reload"); err != nil {
			log("unit-refresh: systemctl daemon-reload (system) failed: %v", err)
		}
	}
	if reloadUser {
		if err := runCmd("systemctl", "--user", "daemon-reload"); err != nil {
			log("unit-refresh: systemctl --user daemon-reload failed: %v", err)
		}
	}

	return rewritten, nil
}

// backupUnit copies the current unit to <path>.citadel-bak so an operator can
// restore their exact prior file. Best-effort atomicity: we write the backup
// fully before the caller overwrites the original.
func backupUnit(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	return os.WriteFile(path+".citadel-bak", data, 0o644)
}

// writeUnitFile atomically writes unit content, preserving the 0644 perms systemd
// units use. Writes to a temp file in the same directory then renames, so a crash
// mid-write can never leave a truncated (unparseable) unit.
func writeUnitFile(path, content string) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".citadel-unit-*.tmp")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(0o644); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("rename unit into place: %w", err)
	}
	return nil
}
