.nh
.TH "CITADEL" "1" "Jan 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-stop - Stop services (all if no service specified, or a specific one)


.SH SYNOPSIS
\fBcitadel stop [service] [flags]\fP


.SH DESCRIPTION
Stops running services.

.PP
When a service name is provided, that specific service is stopped.
When no service is specified, all services in the manifest are stopped.

.PP
Available services: llamacpp, lmstudio, ollama, vllm


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for stop

.PP
\fB--rm\fP[=false]
	Remove the container/volumes after stopping.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--auth-service\fP="https://aceteam.ai"
	The URL of the authentication service

.PP
\fB--config\fP=""
	config file (default is $HOME/.citadel-cli.yaml)

.PP
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--nexus\fP="https://nexus.aceteam.ai"
	The URL of the AceTeam Nexus server


.SH EXAMPLE
.EX
  # Stop a specific service
  citadel stop vllm

  # Stop all services in the manifest
  citadel stop

  # Stop and remove the container
  citadel stop ollama --rm
.EE


.SH SEE ALSO
\fBcitadel(1)\fP
