.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-proxmox - Manage Proxmox VE hypervisor


.SH SYNOPSIS
\fBcitadel proxmox [flags]\fP


.SH DESCRIPTION
Commands for configuring and interacting with a Proxmox VE hypervisor.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for proxmox


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-auto-update\fP[=false]
	Disable automatic update checks and installs for this run (or set CITADEL_NO_AUTO_UPDATE=1)

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel(1)\fP, \fBcitadel-proxmox-forget(1)\fP, \fBcitadel-proxmox-setup(1)\fP, \fBcitadel-proxmox-status(1)\fP
