.nh
.TH "CITADEL" "1" "Jan 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-ping - Ping peers on the AceTeam Network


.SH SYNOPSIS
\fBcitadel ping [ip-or-hostname] [flags]\fP


.SH DESCRIPTION
Pings peer nodes on the AceTeam Network using the internal mesh protocol.

.PP
This works even when standard ICMP ping doesn't, because it uses the WireGuard
tunnel's discovery mechanism.

.PP
With no arguments, pings all online peers once to show network health.


.SH OPTIONS
\fB-c\fP, \fB--count\fP=3
	Number of pings to send

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for ping


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--auth-service\fP="https://aceteam.ai"
	The URL of the authentication service

.PP
\fB--config\fP=""
	config file (default is $HOME/.citadel-cli.yaml)

.PP
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--nexus\fP="https://nexus.aceteam.ai"
	The URL of the AceTeam Nexus server


.SH EXAMPLE
.EX
  citadel ping                  # Ping all online peers
  citadel ping 100.64.0.25      # Ping specific IP
  citadel ping aceteamvm        # Ping by hostname
  citadel ping 100.64.0.25 -c 5 # Ping 5 times
.EE


.SH SEE ALSO
\fBcitadel(1)\fP
