.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-whatsapp-status - Show the WhatsApp bridge status


.SH SYNOPSIS
\fBcitadel whatsapp status [flags]\fP


.SH DESCRIPTION
Show the WhatsApp bridge status


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for status


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-auto-update\fP[=false]
	Disable automatic update checks and installs for this run (or set CITADEL_NO_AUTO_UPDATE=1)

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel-whatsapp(1)\fP
