.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-proxmox-status - Show Proxmox VE status and guests


.SH SYNOPSIS
\fBcitadel proxmox status [flags]\fP


.SH DESCRIPTION
Display the status of the configured Proxmox VE server, including nodes, VMs, and containers.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for status


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel-proxmox(1)\fP
