.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-uninstall-service - Uninstall the Citadel system service (alias for 'service uninstall')


.SH SYNOPSIS
\fBcitadel uninstall-service [flags]\fP


.SH DESCRIPTION
Stop and remove the Citadel managed service.

.PP
This stops the running service, disables auto-start, and removes the service
configuration file. It does NOT remove Citadel config or data.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for uninstall-service


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-auto-update\fP[=false]
	Disable automatic update checks and installs for this run (or set CITADEL_NO_AUTO_UPDATE=1)

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel(1)\fP
