.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-call - Make a direct HTTP call to a peer node via VPN


.SH SYNOPSIS
\fBcitadel call   [flags]\fP


.SH DESCRIPTION
Sends an HTTP request directly to another Citadel node via the
Headscale VPN mesh. Used for inter-node communication, debugging,
and testing specific node endpoints.

.PP
The node must be reachable via its VPN IP address (100.64.x.x).

.PP
Examples:
  # Health check a peer
  citadel call 100.64.0.5 /health

.PP
# Query a database service
  citadel call 100.64.0.5 /api/db/query --method POST --data '{"sql":"SELECT 1"}'

.PP
# Check available services
  citadel call 100.64.0.5 /api/services


.SH OPTIONS
\fB--data\fP=""
	Request body (JSON string)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for call

.PP
\fB--method\fP="GET"
	HTTP method (GET, POST, PUT, DELETE)

.PP
\fB--port\fP=8443
	Target port on the peer node

.PP
\fB--timeout\fP=30000
	Request timeout in milliseconds


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel(1)\fP
