.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-device-run - Run the device daemon (watches the session, self-heals it)


.SH SYNOPSIS
\fBcitadel device run [flags]\fP


.SH DESCRIPTION
Run the device daemon (watches the session, self-heals it)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for run


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-auto-update\fP[=false]
	Disable automatic update checks and installs for this run (or set CITADEL_NO_AUTO_UPDATE=1)

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel-device(1)\fP
