.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-service-catalog-install - Install a service from the catalog onto this node


.SH SYNOPSIS
\fBcitadel service catalog install  [flags]\fP


.SH DESCRIPTION
Install a service from the catalog onto this node


.SH OPTIONS
\fB--allow-privileged\fP[=false]
	Allow a community-source service whose compose requests privileged/root-equivalent access

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for install

.PP
\fB--set\fP=[]
	Set a config value (e.g. --set MODEL=Qwen/Qwen3-8B)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-auto-update\fP[=false]
	Disable automatic update checks and installs for this run (or set CITADEL_NO_AUTO_UPDATE=1)

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel-service-catalog(1)\fP
