.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-rename - Rename this node (OS hostname + Headscale node name)


.SH SYNOPSIS
\fBcitadel rename  [flags]\fP


.SH DESCRIPTION
Renames this Citadel node. This updates:
.IP "  1." 5
The OS hostname (best-effort; requires root on Linux)
.IP "  2." 5
The node name stored in the manifest (citadel.yaml)
.IP "  3." 5
The saved hostname in the global config
.IP "  4." 5
The Headscale node name (by reconnecting to the network)

.PP
The original pre-registration hostname recorded during 'citadel init' is
preserved and can be restored by passing it as \&.

.PP
Examples:
  citadel rename gpu-server-1
  citadel rename --no-reconnect my-node   # update names without reconnecting


.SH OPTIONS
\fB-f\fP, \fB--force\fP[=false]
	Skip the confirmation prompt

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for rename

.PP
\fB--no-reconnect\fP[=false]
	Update local names only; do not reconnect to the network


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel(1)\fP
