.nh
.TH "CITADEL" "1" "Jun 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-update-enable - Enable automatic updates


.SH SYNOPSIS
\fBcitadel update enable [flags]\fP


.SH DESCRIPTION
Enables automatic updates. A running 'citadel work' agent periodically
checks for a newer release and installs it (draining in-flight jobs first).
The setting is persisted and re-read each cycle, so it takes effect on a
running agent without a restart.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for enable


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel-update(1)\fP
