.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-whatsapp-qr - Print the pairing QR for the provisioned tenant


.SH SYNOPSIS
\fBcitadel whatsapp qr [flags]\fP


.SH DESCRIPTION
Print the pairing QR for the provisioned tenant


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for qr


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel-whatsapp(1)\fP
