.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-provision-create - Create a new provisioned resource


.SH SYNOPSIS
\fBcitadel provision create [flags]\fP


.SH DESCRIPTION
Create a Docker container from a spec.

.PP
Examples:
  citadel provision create --name my-app --image nginx:latest
  citadel provision create --name db --image postgres:16 --port 5432:5432 --env POSTGRES_PASSWORD=secret
  citadel provision create --name gpu-worker --image pytorch/pytorch --gpus all


.SH OPTIONS
\fB--cmd\fP=[]
	Override container command

.PP
\fB--cpus\fP=""
	CPU limit (e.g., 0.5)

.PP
\fB-e\fP, \fB--env\fP=[]
	Environment variable (KEY=VALUE)

.PP
\fB--gpus\fP=""
	GPU access (e.g., all, 1)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for create

.PP
\fB--image\fP=""
	Container image (required)

.PP
\fB--memory\fP=0
	Memory limit in MB

.PP
\fB--name\fP=""
	Resource name (required)

.PP
\fB-p\fP, \fB--port\fP=[]
	Port mapping (host:container[/protocol])

.PP
\fB-v\fP, \fB--volume\fP=[]
	Volume mount (host:container[:ro])


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-auto-update\fP[=false]
	Disable automatic update checks and installs for this run (or set CITADEL_NO_AUTO_UPDATE=1)

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel-provision(1)\fP
