.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-module-list - List installed modules (services in the node manifest)


.SH SYNOPSIS
\fBcitadel module list [flags]\fP


.SH DESCRIPTION
List installed modules (services in the node manifest)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list

.PP
\fB--outdated\fP[=false]
	Check each installed module against its source and mark outdated ones.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel-module(1)\fP
