.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-service - Manage Citadel as a system service


.SH SYNOPSIS
\fBcitadel service [flags]\fP


.SH DESCRIPTION
Install, uninstall, start, stop, or check the status of Citadel as a system service.

.PP
This allows Citadel to run in the background and start automatically on boot.

.PP
On Linux:   Creates a systemd unit (user unit by default, --system for system-wide)
On macOS:   Creates a launchd plist (user agent by default, --system for daemon)
On Windows: Creates a Windows Service (always system-wide)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for service


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel(1)\fP, \fBcitadel-service-catalog(1)\fP, \fBcitadel-service-install(1)\fP, \fBcitadel-service-start(1)\fP, \fBcitadel-service-status(1)\fP, \fBcitadel-service-stop(1)\fP, \fBcitadel-service-uninstall(1)\fP
