.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-whatsapp-connect - Print the api_url + api_key to register via whatsapp_connect


.SH SYNOPSIS
\fBcitadel whatsapp connect [flags]\fP


.SH DESCRIPTION
Print the api_url + api_key to register via whatsapp_connect


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for connect


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel-whatsapp(1)\fP
