.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-tmux-status - Show how tmux is resolved on this node


.SH SYNOPSIS
\fBcitadel tmux status [flags]\fP


.SH DESCRIPTION
Show how tmux is resolved on this node


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for status


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel-tmux(1)\fP
