.nh
.TH "CITADEL" "1" "Jun 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-app - Manage developer tool apps on this node


.SH SYNOPSIS
\fBcitadel app [flags]\fP


.SH DESCRIPTION
Install, manage, and remove developer tool applications on your Citadel node.

.PP
Apps run as Docker containers and are accessible via your browser. Data is
persisted in ~/.citadel/apps//data/ so it survives restarts.

.PP
Available apps: code-server, jupyter, filebrowser, ollama-webui


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for app


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--auth-service\fP="https://aceteam.ai"
	The URL of the authentication service

.PP
\fB--config\fP=""
	config file (default is $HOME/.citadel-cli.yaml)

.PP
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--nexus\fP="https://nexus.aceteam.ai"
	The URL of the AceTeam Nexus server

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel(1)\fP, \fBcitadel-app-install(1)\fP, \fBcitadel-app-list(1)\fP, \fBcitadel-app-start(1)\fP, \fBcitadel-app-status(1)\fP, \fBcitadel-app-stop(1)\fP, \fBcitadel-app-uninstall(1)\fP
