.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-module-search - Search the curated module index by name, description, or tag


.SH SYNOPSIS
\fBcitadel module search [query] [flags]\fP


.SH DESCRIPTION
Search the curated central index for installable modules.

.PP
The index maps module names to source repos, descriptions, and tags. Results
show the install source and whether that source is already trusted on this node
(see 'citadel module trust'). Install a result with:

.PP
citadel module install 

.PP
If no index has been published yet (or the catalog has not been cloned), this
prints a friendly hint instead of an error. Run 'citadel service catalog update'
to fetch the latest catalog (which carries the index).


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for search


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel-module(1)\fP
