.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-module-untrust - Remove a pattern from the trusted-source allowlist


.SH SYNOPSIS
\fBcitadel module untrust  [flags]\fP


.SH DESCRIPTION
Remove a pattern from the trusted-source allowlist


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for untrust


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel-module(1)\fP
