.nh
.TH "CITADEL" "1" "Jun 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-app-list - Show available apps with install status


.SH SYNOPSIS
\fBcitadel app list [flags]\fP


.SH DESCRIPTION
Show available apps with install status


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel-app(1)\fP
