.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-service-catalog-list-sources - List configured catalog sources


.SH SYNOPSIS
\fBcitadel service catalog list-sources [flags]\fP


.SH DESCRIPTION
List configured catalog sources


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list-sources


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel-service-catalog(1)\fP
