.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-service-install - Install Citadel as a system service


.SH SYNOPSIS
\fBcitadel service install [flags]\fP


.SH DESCRIPTION
Install Citadel as a managed background service that runs on boot.

.PP
By default installs as a user service (no root/admin required on Linux/macOS).
Use --system to install as a system-wide service (requires root/admin).

.PP
The service runs "citadel work" with the CITADEL_SERVICE=true environment
variable set, enabling auto-restart on failure and boot-time startup.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for install

.PP
\fB--system\fP[=false]
	Install as a system-wide service (requires root/admin)

.PP
\fB--user\fP[=false]
	Install as a user service (default on Linux/macOS)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-auto-update\fP[=false]
	Disable automatic update checks and installs for this run (or set CITADEL_NO_AUTO_UPDATE=1)

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel-service(1)\fP
