.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-service-catalog-info - Show full details about a catalog service


.SH SYNOPSIS
\fBcitadel service catalog info  [flags]\fP


.SH DESCRIPTION
Show full details about a catalog service


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for info


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel-service-catalog(1)\fP
