.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-provision-logs - View logs from a provisioned resource


.SH SYNOPSIS
\fBcitadel provision logs  [flags]\fP


.SH DESCRIPTION
View logs from a provisioned resource


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for logs

.PP
\fB--tail\fP=100
	Number of log lines to show


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-auto-update\fP[=false]
	Disable automatic update checks and installs for this run (or set CITADEL_NO_AUTO_UPDATE=1)

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel-provision(1)\fP
