.nh
.TH "CITADEL" "1" "Jul 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-module-gc - Remove module cache directories not referenced by the lockfile


.SH SYNOPSIS
\fBcitadel module gc [flags]\fP


.SH DESCRIPTION
Remove module cache directories not referenced by the lockfile


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for gc


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--no-color\fP[=false]
	Disable colorized output


.SH SEE ALSO
\fBcitadel-module(1)\fP
