.nh
.TH "CITADEL" "1" "Jan 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-expose - Show access information for this node and network peers


.SH SYNOPSIS
\fBcitadel expose [port] [flags]\fP


.SH DESCRIPTION
Shows network access information for this node and services on the AceTeam Network.

.PP
Without arguments, displays this node's network IP and common service URLs.
Use --peers to see services available on other nodes in your network.
Use --check to verify that services are actually reachable.


.SH OPTIONS
\fB--check\fP[=false]
	Verify service reachability (can combine with --peers)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for expose

.PP
\fB--peers\fP[=false]
	Show services available on all network peers

.PP
\fB--service\fP=""
	Show access info for a known service (vllm, ollama, llamacpp, lmstudio)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--auth-service\fP="https://aceteam.ai"
	The URL of the authentication service

.PP
\fB--config\fP=""
	config file (default is $HOME/.citadel-cli.yaml)

.PP
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--nexus\fP="https://nexus.aceteam.ai"
	The URL of the AceTeam Nexus server


.SH EXAMPLE
.EX
  # Show this node's access info (network IP and common service URLs)
  citadel expose

  # Show services available on all peers
  citadel expose --peers

  # Show this node's services and verify they're reachable
  citadel expose --check

  # Show peer services with reachability check
  citadel expose --peers --check
.EE


.SH SEE ALSO
\fBcitadel(1)\fP
