.nh
.TH "CITADEL" "1" "Jan 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-update-rollback - Restore the previous version


.SH SYNOPSIS
\fBcitadel update rollback [flags]\fP


.SH DESCRIPTION
Restores the previously installed version of Citadel CLI.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for rollback


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--auth-service\fP="https://aceteam.ai"
	The URL of the authentication service

.PP
\fB--config\fP=""
	config file (default is $HOME/.citadel-cli.yaml)

.PP
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--nexus\fP="https://nexus.aceteam.ai"
	The URL of the AceTeam Nexus server


.SH SEE ALSO
\fBcitadel-update(1)\fP
