.nh
.TH "CITADEL" "1" "Jan 2026" "AceTeam" "Citadel CLI Manual"

.SH NAME
citadel-login - Authenticate this machine with the AceTeam Network


.SH SYNOPSIS
\fBcitadel login [flags]\fP


.SH DESCRIPTION
Connects this machine to your AceTeam network. If already connected, it does
nothing. Otherwise, it interactively prompts for an authentication method.

.PP
Use --authkey for non-interactive authentication (ideal for automation).


.SH OPTIONS
\fB--authkey\fP=""
	Pre-generated authkey for non-interactive login

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for login

.PP
\fB--node-name\fP=""
	Override the node name (defaults to hostname)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--auth-service\fP="https://aceteam.ai"
	The URL of the authentication service

.PP
\fB--config\fP=""
	config file (default is $HOME/.citadel-cli.yaml)

.PP
\fB--debug\fP[=false]
	Enable debug output

.PP
\fB--nexus\fP="https://nexus.aceteam.ai"
	The URL of the AceTeam Nexus server


.SH EXAMPLE
.EX
  # Interactive login (prompts for auth method)
  citadel login

  # Non-interactive login with authkey (for automation)
  citadel login --authkey tskey-auth-xxx

  # Override the node name
  citadel login --authkey tskey-auth-xxx --node-name my-gpu-server
.EE


.SH SEE ALSO
\fBcitadel(1)\fP
