//go:build ignore

// gen-manpage.go generates man pages for the citadel CLI.
// Run with: go run docs/gen-manpage.go
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/aceteam-ai/citadel-cli/cmd"
	"github.com/spf13/cobra/doc"
)

func main() {
	// Get output directory from args or use default
	outDir := "docs/man"
	if len(os.Args) > 1 {
		outDir = os.Args[1]
	}

	// Create output directory
	if err := os.MkdirAll(outDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating directory %s: %v\n", outDir, err)
		os.Exit(1)
	}

	// Set up man page header
	header := &doc.GenManHeader{
		Title:   "CITADEL",
		Section: "1",
		Source:  "AceTeam",
		Manual:  "Citadel CLI Manual",
		Date:    timePtr(time.Now()),
	}

	// Get the root command
	rootCmd := cmd.GetRootCmd()

	// Disable auto-generated "Auto generated by spf13/cobra" text
	rootCmd.DisableAutoGenTag = true

	// Generate man pages for all commands
	if err := doc.GenManTree(rootCmd, header, outDir); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating man pages: %v\n", err)
		os.Exit(1)
	}

	// List generated files
	files, _ := filepath.Glob(filepath.Join(outDir, "*.1"))
	fmt.Printf("Generated %d man pages in %s:\n", len(files), outDir)
	for _, f := range files {
		fmt.Printf("  - %s\n", filepath.Base(f))
	}
}

func timePtr(t time.Time) *time.Time {
	return &t
}
